# This is a basic workflow to help you get started with Actions

name: Deploy to Google App Engine

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # CODE BY ME HERE
            - name: get appp.yml
              run: echo " ${{ secrets.APP_YML }} " > app.yaml
              
            - name: setup nodejs
              uses: actions/setup-node@v2.1.5
              
            - name: install packages
              run: yarn install
              
            - name: build typescript
              run: yarn build

            - uses: google-github-actions/deploy-appengine@main
              with:
                  deliverables: app.yaml
                  project_id: ${{ secrets.GCP_PROJECT }}
                  credentials: ${{ secrets.GCP_SA_KEY }}

            - name: log on discord
              run: |
                  curl --request POST \
                  --url https://discord.com/api/webhooks/782598319323086868/LWwBCTYSM6M3uiF_42x3ZByWmq_ERfq-UehLmv_bCpzSFtxH4SaAem91kDNfVscSWikh \
                  --header 'Content-Type: application/json' \
                  --cookie '__cfduid=d1e7a5c64bc2f56c01ea5591b075b95cd1614172011; __cfruid=04c218a326cc7b1f058bd1659507ccd43ae8b48b-1614172011' \
                  --data '{	"content":"Deployed Successfully!","username":"App Engine","avatar_url":"https://i.imgur.com/WxZzTz8.png"}'
                  
